title: AIE Models
subtitle: Comparison of AIE Models and model tooling a.o. listed AINativeDev AIE/Model category.
selectTitle: Filter Criteria
tableTitle: Comparison of AIE Models
criteria:
  - Notes:
      name: Notes
      type: MARKDOWN
      search: false
      table: false
      detail: true
      andSearch: false
      rangeSearch: false
      order: 0
      description: ""
      placeholder: ""
  - Last Update:
      name: Last Update
      type: MARKDOWN
      search: false
      table: true
      detail: true
      andSearch: false
      rangeSearch: false
      order: 0
      description: Note Date last updated
      placeholder: ""
