title: Product Prototyping
subtitle: Comparison of Product builders suited for Prototyping a.o. listed AINativeDev Product/Prototyping category.
selectTitle: Filter Criteria
tableTitle: Comparison of AI Code Editors
criteria:
  - Terminal:
      name: Terminal
      type: LABEL
      search: true
      table: true
      detail: true
      description: 'Coding tool can operate in a terminal/cli environment'
      placeholder: &ref_1
        template: 'Select {} ...'
        variables:
          - name
      order: '20'
      andSearch: false
      rangeSearch: false
      values:
        'Yes':
        'No':
  - SpecDrivenDevelopment:
      name: SpecDrivenDevelopment
      type: LABEL
      search: true
      table: true
      detail: true
      description: 'Has support for these Spec Driven Development methodologies:'
      placeholder: *ref_1
      order: '60'
      andSearch: false
      rangeSearch: false
      values:
        'BMAD':
        'SpecKit':
        'OpenSpec':
        'Tessl':
        'AgentOS':
        'ClaudeFlow':
        'SPARC':
        'SuperClaude':
